MovieWebsite/Controllers/GenresController.cs
using BusinessObject.Models;
using DataAccess.Repository;
using DataAccess.Repository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MovieWebsite.Controllers
{

    public class GenresController : BaseController
    {

        IGenreRepository genreRepository = null!;
        private static readonly string SUCCESS="Action complete successfully!";

        public GenresController()
        {
            genreRepository = new GenreRepository();
        }

        // GET: GenresController
        public ActionResult Index(string? message)
        {
            var genres= genreRepository.GetGenres();
            ViewBag.Message = message;
            return View(genres);
        }

        // GET: GenresController/Details/5
        public ActionResult Details(int id)
        {
            return RedirectToAction(nameof(Index));
        }

        // POST: GenresController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string genreName)
        {
            try
            {
                if (String.IsNullOrEmpty(genreName))
                {
                    throw new Exception("Genre name can not be empty");
                }
                var genre = new Genre {
                    Id=genreName.Trim().ToLower(),
                    Name = genreName,
                };
                var genreExisting = await genreRepository.GetGenreByNameAsync(genreName);
                if (genreExisting != null)
                {
                    throw new Exception("This genre has already existed!");
                }
                else
                {
                    await genreRepository.AddGenre(genre);
                }
                return RedirectToAction(nameof(Index), new {message= SUCCESS });
            }
            catch(Exception ex)
            {
                return RedirectToAction(nameof(Index), new {message= ex.Message });
            }
        }

        // GET: GenresController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            try
            {
                var genre = await genreRepository.GetGenreByIdAsync(id);
                return View(genre);
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            
        }

        // POST: GenresController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, Genre genreInput)
        {
            try
            {
                var genre = await genreRepository.GetGenreByNameAsync(genreInput.Name);
                if (genre != null)
                {
                    throw new Exception("This genre has already existed!");
                }
                await genreRepository.Update(genreInput);
                return RedirectToAction(nameof(Index), new {message= SUCCESS });
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("Name", ex.Message);
                return View(genreInput);
            }
        }

        // GET: GenresController/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                var genre = await genreRepository.GetGenreByIdAsync(id);
                return View(genre);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // POST: GenresController/Delete/5
        [HttpPost, ActionName(nameof(Delete))]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAsync(string id, Genre genreInput)
        {
            try
            {
                var genre = await genreRepository.GetGenreByIdAsync(id);
                await genreRepository.Delete(genre);
                return RedirectToAction(nameof(Index), new { message = SUCCESS });
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(genreInput);
            }
        }
    }
}

MovieWebsite/Controllers/PeopleController.cs
using BusinessObject.Models;
using DataAccess.Repository;
using DataAccess.Repository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MovieWebsite.Controllers
{

    public class PeopleController : BaseController
    {

        IPeopleRepository PeopleRepository = null!;
        private static readonly string SUCCESS="Action complete successfully!";

        public PeopleController()
        {
            PeopleRepository = new PeopleRepository();
        }

        // GET: PeoplesController
        public ActionResult Index(string? message)
        {
            var Peoples= PeopleRepository.GetPeoples();
            ViewBag.Message = message;
            return View(Peoples);
        }

        // GET: PeoplesController/Details/5
        public ActionResult Details(int id)
        {
            return RedirectToAction(nameof(Index));
        }

        // POST: PeoplesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string PeopleName)
        {
            try
            {
                if (String.IsNullOrEmpty(PeopleName))
                {
                    throw new Exception("People name can not be empty");
                }
                var People = new People {
                    Id=PeopleName.Trim().ToLower(),
                    Name = PeopleName,
                };
                var PeopleExisting = await PeopleRepository.GetPeopleByIdAsync(PeopleName);
                if (PeopleExisting != null)
                {
                    throw new Exception("This People has already existed!");
                }
                else
                {
                    await PeopleRepository.AddPeople(People);
                }
                return RedirectToAction(nameof(Index), new {message= SUCCESS });
            }
            catch(Exception ex)
            {
                return RedirectToAction(nameof(Index), new {message= ex.Message });
            }
        }

        // GET: PeoplesController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            try
            {
                var People = await PeopleRepository.GetPeopleByIdAsync(id);
                return View(People);
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            
        }

        // POST: PeoplesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, People PeopleInput)
        {
            try
            {
                var People = await PeopleRepository.GetPeopleByIdAsync(PeopleInput.Name);
                if (People != null)
                {
                    throw new Exception("This People has already existed!");
                }
                await PeopleRepository.Update(PeopleInput);
                return RedirectToAction(nameof(Index), new {message= SUCCESS });
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("Name", ex.Message);
                return View(PeopleInput);
            }
        }

        // GET: PeoplesController/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                var People = await PeopleRepository.GetPeopleByIdAsync(id);
                return View(People);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // POST: PeoplesController/Delete/5
        [HttpPost, ActionName(nameof(Delete))]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAsync(string id, People PeopleInput)
        {
            try
            {
                var People = await PeopleRepository.GetPeopleByIdAsync(id);
                await PeopleRepository.Delete(People);
                return RedirectToAction(nameof(Index), new { message = SUCCESS });
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(PeopleInput);
            }
        }
    }
}

MovieWebsite/Controllers/RolesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieWebsite.Enums;

namespace MovieWebsite.Controllers
{
    public class RolesController : BaseController
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        // GET: RoleManagerController
        public async Task<IActionResult> Index(bool? result)
        {
            List<IdentityRole> roles=new();
            try
            {
                roles = await _roleManager.Roles.ToListAsync();
                ViewData["CreateResult"] = result;
                if (result == true)
                {
                    ViewBag.Message = "Thao tác thành công!";
                }
                if(result == false)
                {
                    ViewBag.Message = "Error: Không thể để role trống";
                }
            }
            catch(Exception ex)
            {
                ViewBag.Message = "Error:"+ ex.Message;
            }
            return View(roles);
        }

        // GET: RoleManagerController/Details/5
        public async Task<IActionResult> Details(string id)
        {
            var role=await _roleManager.FindByIdAsync(id);
            return View(role);
        }

        // GET: RoleManagerController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RoleManagerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string roleName)
        {
            bool result = false;
            if (roleName!=null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
                result = true;
            }
            return RedirectToAction(nameof(Index), new { result });
        }

        // GET: RoleManagerController/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            return View(role);
        }

        // POST: RoleManagerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, IdentityRole roleNew)
        {
            if (ModelState.IsValid)
            {
                var role=await _roleManager.FindByIdAsync(id);
                role.Name = roleNew.Name;
                role.ConcurrencyStamp = roleNew.ConcurrencyStamp;
                role.NormalizedName = roleNew.Name.Normalize();
                var result = await _roleManager.UpdateAsync(role);
                return RedirectToAction(nameof(Index), new { result = result.Succeeded });
            }
            return View();
        }

        // GET: RoleManagerController/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            return View(role);
        }

        // POST: RoleManagerController/Delete/5
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(string id)
        {
            try
            {
                var role = await _roleManager.FindByIdAsync(id);
                var result=await _roleManager.DeleteAsync(role);
                return RedirectToAction(nameof(Index), new { result = result.Succeeded });
            }
            catch
            {
                return View();
            }
        }
    }
}

MovieWebsite/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Not Found";
    var errorMessage = ViewBag.ErrorMessage;
    var path = ViewBag.Path;
    var qs = ViewBag.QS;
}
<h1>
    @errorMessage
</h1>
<h2>
    @path@qs
</h2>
<a asp-action="Index" asp-controller="Movies">
    Click here to navigate back to the home page
</a>

MovieWebsite/Views/Shared/_FollowedMovieList.cshtml
@{
    List<Movie> followedMovies = ViewBag.FollowedMovies;
}
@if (followedMovies != null)
{
    if (User.Identity!.IsAuthenticated)
    {
        <div class="dropdown show">
            <a class="btn btn-sm btn-primary dropdown-toggle" title="Danh sách phim theo dõi" 
            href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-bookmark" aria-hidden="true"></i>
                <span class="badge badge-pill badge-info">@followedMovies.Count</span>
            </a>
            <div class="dropdown-menu" style="width:20rem" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header row justify-content-center">
                    <a role="button" class="col-md-4 fw-bold">Danh sách phim theo dõi</a>
                </div>
                <div class="dropdown-divider"></div>
                <div style="height: 15rem;overflow-y: scroll;overflow-x: clip;">
                    @foreach (var movie in followedMovies)
                    {
                        <div class="dropdown small">
                            <a class=" nav-link text-dark hstack gap-1" asp-action="Details" asp-route-id="@movie.Id">
                                <img class="movie-icon img-thumbnail rounded" decoding="async" src="@("~/image/"+movie.ImageName)" asp-append-version="true" alt="Card cover image">
                                <dl class="row">
                                    <dt class="col-md-12">
                                        @movie.Title
                                    </dt>
                                    <dd class="col-md-12">
                                        @movie.Views Lượt xem
                                    </dd>
                                </dl>
                            </a>
                        </div>
                    }
                </div>
            </div>
        </div>
    }
}

MovieWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieWebsite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="//use.fontawesome.com/releases/v5.7.2/css/all.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieWebsite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">MovieWebsite</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>
                        @if(User.Identity!.IsAuthenticated){
                            if(User.IsInRole(Roles.SuperAdmin.ToString())){
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Genres" asp-action="Index">Genres</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">Peoples</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">User Roles</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="UserRoles" asp-action="Index">Users</a>
                                </li>
                            }
                        }
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        @*<form class="input-group " asp-controller="Movies" asp-action="Index">
                            <input class="form-control mr-sm-2" name="searchString" type="search" placeholder="Search" value="@ViewBag.SearchString" aria-label="Search">
                            <span class="input-group-btn">
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                            </span>
                        </form>*@
                        <li class="nav-item" style="width:100%">
                            <div class="gcse-searchbox-only" enableAutoComplete="true" data-resultsUrl="@Url.Action("Index","Movies")" data-queryParameterName="searchString" />
                        </li>
                        <li class="nav-item">
                            <partial name="_FollowedMovieList" />
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
        <partial name="_NavBarSecondary" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MovieWebsite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script async src="https://cse.google.com/cse.js?cx=659edb2ea7f8b4f62"></script>
    <script>
        window.onload= function(){
            document.getElementById('gsc-i-id1').placeholder = 'Enter keywords (movie title, people).';
        };
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieWebsite/Views/Shared/_Message.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        @Model
    </div>
}

MovieWebsite/Views/Shared/_NavBarSecondary.cshtml
@{
    var genreList = ViewBag.GenreNavBar;
    var nationList = ViewBag.NationNavBar;
}
@if(genreList!=null){
    <nav class="navbar navbar-collapse navbar-expand-sm navbar-toggleable-sm collapse d-sm-inline-flex justify-content-between navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Trang chủ</a>
                </li>
                <li class="nav-item dropdown ">
                    <a class="nav-link text-dark btn dropdown-toggle" role="button" data-bs-toggle="dropdown" id="genres" aria-expanded="false">Thể loại</a>
                    <div class="dropdown-menu" aria-labelledby="#genres">
                        @foreach (var genre in genreList)
                        {
                            <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Movies" asp-action="Index" asp-route-genreName="@genre.Name">@genre.Name</a>
                        }
                    </div>
                </li>
                <li class="nav-item dropdown ">
                    <a class="nav-link text-dark btn dropdown-toggle" role="button" data-bs-toggle="dropdown" id="nations" aria-expanded="false">Quốc gia</a>
                    <div class="dropdown-menu" aria-labelledby="#nations">
                        @foreach (var nation in nationList)
                        {
                            <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Movies" asp-action="Index" asp-route-nation="@nation">@nation</a>
                        }
                    </div>
                </li>
            </ul>
        </div>
    </nav>
}