MovieWebsite/Models/Movies/ManageMovieGenreViewModel.cs
namespace MovieWebsite.Models.Movies
{
    public class ManageMovieGenreViewModel
    {
        public string Name { get; set; } = null!;
        public bool Selected { get; set; } = false;
    }
}

MovieWebsite/Models/Movies/ManageMoviePeopleModel.cs
namespace MovieWebsite.Models.Movies
{
    public class ManageMoviePeopleModel
    {
        public string Name { get; set; } = null!;
        public string RoleId { get; set; } = null!;
        public bool Selected { get; set; } = false;
    }
}

MovieWebsite/Models/Movies/ManageMovieStatusModel.cs
namespace MovieWebsite.Models.Movies
{
    public class ManageMovieStatusModel
    {
        public string Name { get; set; } = null!;
        public bool Selected { get; set; } = false;
    }
}

MovieWebsite/Models/Movies/MovieInputModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MovieWebsite.Models.Movies
{
    public class MovieInputModel
    {
        public string Id { get; set; } = null!;
        [DisplayName("Tựa đề")]
        public string Title { get; set; }
        [DisplayName("Cover")]
        public string? ImageName { get; set; } = null!;
        [DisplayName("Thể loại")]
        public virtual List<ManageMovieGenreViewModel> Genres { get; set; }=null!;

        [NotMapped]
        [DisplayName("Cover")]
        public IFormFile? ImageFile { get; set; }

        [DisplayName("Nội dung")]
        public string? Description { get; set; } = null!;
        [DisplayName("Năm phát hành")]
        [Range(1906,3000)]
        public int? ReleaseYear { get; set; }
        [DisplayName("Thời lượng")]
        public string? Duration { get; set; } = null!;
        [DisplayName("Quốc gia")]
        public string? Nation { get; set; } = null!;

        public virtual List<ManageMoviePeopleModel> MoviePeople { get; set; } = null!;
        public virtual List<ManageMovieStatusModel> MovieStatuses { get; set; } = null!;
    }
}

MovieWebsite/Models/Movies/MovieSuggestModel.cs
using BusinessObject.Models;

namespace MovieWebsite.Models.Movies
{
    public class MovieSuggestModel
    {
        public string Title { get; set; } = null!;
        public IEnumerable<Movie> MoviesSuggestion { get; set; } = null!;
    }
}

MovieWebsite/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using DataAccess.Repository;
using MovieWebsite.Models.Movies;
using DataAccess.Repository.Interface;
using BusinessObject.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http.Extensions;
using MovieWebsite.Enums;

namespace MovieWebsite.Controllers
{
    public class MoviesController : BaseController
    {
        private readonly IMovieRepository movieRepository=null!;
        private readonly IGenreRepository genreRepository = null!;
        private readonly IMovieGenreRepository movieGenreRepository = null!;
        private readonly IApplicationUserRepository applicationUserRepository = null!;
        private readonly ICommentRepository commentRepository = null!;
        private readonly IEpisodeRepository episodeRepository;
        private readonly IWebHostEnvironment _environment;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IRoleRepository roleRepository;
        private readonly IPeopleRepository peopleRepository;
        private readonly IMoviePeopleRepository moviePeopleRepository;
        private readonly IMovieStatusRepository movieStatusRepository;
        private readonly IStatusRepository statusRepository;
        private readonly IRateRepository rateRepository;
        private readonly IFollowedMovieRepository followedMovieRepository;
        public MoviesController(IWebHostEnvironment environment, UserManager<ApplicationUser> userManager)
        {
            movieRepository = new MovieRepository();
            genreRepository = new GenreRepository();
            movieGenreRepository = new MovieGenreRepository();
            applicationUserRepository = new ApplicationUserRepository();
            commentRepository = new CommentRepository();
            episodeRepository = new EpisodeRepository();
            moviePeopleRepository= new MoviePeopleRepository();
            peopleRepository = new PeopleRepository();
            roleRepository = new RoleRepository();
            movieStatusRepository= new MovieStatusRepository();
            statusRepository= new StatusRepository();
            rateRepository= new RateRepository();
            followedMovieRepository= new FollowedMovieRepository();
            _environment = environment;
            _userManager = userManager;
        }
        [AllowAnonymous]
        // GET: MoviesController1
        public IActionResult Index(string? searchString, string? genreName, string? message, string? nation, IFormCollection collection)
        {
            List<MovieViewModel> model = new();
            try
            {
                IEnumerable<Movie> movies=movieRepository.GetMovies();
                var temp = movies.ToList();
                IEnumerable<Movie> searchResult;
                IEnumerable<Movie> filterResult;
                IEnumerable<Movie> nationResult;
                if (searchString != null)
                {
                    searchResult = movieRepository.GetMoviesByKeyWord(searchString).ToList();
                    movies=movies.IntersectBy(second:searchResult.Select(m=>m.Id), m => m.Id);
                    ViewBag.SearchString = searchString;
                }
                if (genreName != null)
                {
                    filterResult = movieRepository.GetMoviesByGenre(genreName).ToList();
                    movies = movies.IntersectBy(second: filterResult.Select(m => m.Id), m => m.Id);
                }
                if (nation != null)
                {
                    nationResult = movieRepository.GetMovies().Where(m => m.Nation == nation).ToList();
                    movies = movies.IntersectBy(second: nationResult.Select(m => m.Id), m => m.Id);
                }
                if(movies.Count() < temp.Count)
                {
                    ViewBag.ResetList = true;
                }
                if (movies.Any())
                {
                    foreach (var movie in movies)
                    {
                        var viewModel =GenerateMovieViewModel(movie);
                        model.Add(viewModel);
                    }
                }
                else
                {
                    throw new Exception("Sorry, we could not find your movie!");
                }
                ViewBag.Message = message;
            }
            catch (Exception ex)
            {
                ViewBag.Message=ex.Message;
            }
            return View(model);
        }
        [AllowAnonymous]
        // GET: MoviesController1/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (movieRepository.GetMovies() == null)
            {
                return View(null);
            }
            var movie = await movieRepository.GetMovieByIdAsync(id);
            var count = movie.Rates.Count;
            if (count > 0)
            {
                movie.Rating = (float)movie.Rates.Select(m => m.Rating).Sum()! /count;
                await movieRepository.Update(movie);
            }
            var movieView =GenerateMovieViewModel(movie);
            ViewBag.MovieRoles = roleRepository.GetRoles();
            return View(movieView);
        }

        // GET: MoviesController1/Create
        public IActionResult Create()
        {
            var movieInput = GenerateMovieInputModel();
            return View(movieInput);
        }

        // POST: MoviesController1/Create
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync(MovieInputModel movieInput)
        {
            try
            {
                movieInput.Id = movieInput.Title.Trim().ToLower();
                if (await ExistedTitleAsync(movieInput.Id))
                {
                    var movie = new Movie
                    {
                        Title = movieInput.Title,
                        Id = movieInput.Id,
                        Description = movieInput.Description,
                        ReleaseYear = movieInput.ReleaseYear,
                        Duration = movieInput.Duration,
                        Nation = movieInput.Nation,
                    };
                    if (movieInput.ImageFile != null)
                    {
                        movie.ImageName = await GetFileNameAsync(movieInput.ImageFile);
                        await AddSelectedAsync(movieInput);
                        await movieRepository.AddMovie(movie);
                    }
                    else
                    {
                        ModelState.AddModelError("ImageFile", "This field must not be leave empty!");
                        throw new Exception();
                    }
                }
                return RedirectToAction(nameof(Index), new { message = "Create successfully" });
            }
            catch
            {
                movieInput =GenerateMovieInputModel();
                return View(movieInput);
            }
        }

        // GET: MoviesController1/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            //find movie
            var movie = await movieRepository.GetMovieByIdAsync(id);
            MovieInputModel inputModel;
            if (movie == null)
            {
                return NotFound();
            }
            inputModel = GenerateMovieInputModel(movie);
            ViewBag.MovieRoles=roleRepository.GetRoles();
            //set datalist
            return View(inputModel);
        }

        // POST: MoviesController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MovieInputModel movieInput)
        {
            try
            {
                var movie = await movieRepository.GetMovieByIdAsync(movieInput.Id);
                if (movie == null)
                {
                    return NotFound();
                }
                //update movie----------------------------
                movie.Title = movieInput.Title;
                movie.Description = movieInput.Description;
                movie.ReleaseYear = movieInput.ReleaseYear;
                movie.Duration=movieInput.Duration;
                movie.Nation = movieInput.Nation;
                if (movieInput.ImageFile != null)
                {
                    RemoveImageFile(movie.ImageName);
                    movie.ImageName = await GetFileNameAsync(movieInput.ImageFile);
                }
                await movieRepository.Update(movie);
                //add selected genre-----------------------
                var movieGenres = movieGenreRepository.GetMovieGenresByMovieId(movieInput.Id);
                await movieGenreRepository.DeleteRange(movieGenres);
                var genres = movieInput.Genres.Where(m => m.Selected).Select(m => m.Name);
                foreach (var genreName in genres)
                {
                    var genre = await genreRepository.GetGenreByNameAsync(genreName);
                    var movieGenre = new MovieGenre
                    {
                        GenreId = genre.Id,
                        MovieId = movie.Id,
                        Id = movie.Id + genre.Id,
                    };
                    await movieGenreRepository.AddMovieGenre(movieGenre);
                }
                //add selected people----------------------
                var removedPeople= moviePeopleRepository.GetMoviePeople().Where(m=>m.MovieId==movieInput.Id).ToList();
                await moviePeopleRepository.DeleteRange(removedPeople);
                var peopleList = movieInput.MoviePeople.Where(m => m.Selected);
                foreach(var p in peopleList)
                {

MovieWebsite/Controllers/PeopleController.cs
using BusinessObject.Models;
using DataAccess.Repository;
using DataAccess.Repository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MovieWebsite.Controllers
{

    public class PeopleController : BaseController
    {

        IPeopleRepository PeopleRepository = null!;
        private static readonly string SUCCESS="Action complete successfully!";

        public PeopleController()
        {
            PeopleRepository = new PeopleRepository();
        }

        // GET: PeoplesController
        public ActionResult Index(string? message)
        {
            var Peoples= PeopleRepository.GetPeoples();
            ViewBag.Message = message;
            return View(Peoples);
        }

        // GET: PeoplesController/Details/5
        public ActionResult Details(int id)
        {
            return RedirectToAction(nameof(Index));
        }

        // POST: PeoplesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string PeopleName)
        {
            try
            {
                if (String.IsNullOrEmpty(PeopleName))
                {
                    throw new Exception("People name can not be empty");
                }
                var People = new People {
                    Id=PeopleName.Trim().ToLower(),
                    Name = PeopleName,
                };
                var PeopleExisting = await PeopleRepository.GetPeopleByIdAsync(PeopleName);
                if (PeopleExisting != null)
                {
                    throw new Exception("This People has already existed!");
                }
                else
                {
                    await PeopleRepository.AddPeople(People);
                }
                return RedirectToAction(nameof(Index), new {message= SUCCESS });
            }
            catch(Exception ex)
            {
                return RedirectToAction(nameof(Index), new {message= ex.Message });
            }
        }

        // GET: PeoplesController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            try
            {
                var People = await PeopleRepository.GetPeopleByIdAsync(id);
                return View(People);
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            
        }

        // POST: PeoplesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, People PeopleInput)
        {
            try
            {
                var People = await PeopleRepository.GetPeopleByIdAsync(PeopleInput.Name);
                if (People != null)
                {
                    throw new Exception("This People has already existed!");
                }
                await PeopleRepository.Update(PeopleInput);
                return RedirectToAction(nameof(Index), new {message= SUCCESS });
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("Name", ex.Message);
                return View(PeopleInput);
            }
        }

        // GET: PeoplesController/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                var People = await PeopleRepository.GetPeopleByIdAsync(id);
                return View(People);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // POST: PeoplesController/Delete/5
        [HttpPost, ActionName(nameof(Delete))]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAsync(string id, People PeopleInput)
        {
            try
            {
                var People = await PeopleRepository.GetPeopleByIdAsync(id);
                await PeopleRepository.Delete(People);
                return RedirectToAction(nameof(Index), new { message = SUCCESS });
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(PeopleInput);
            }
        }
    }
}

MovieWebsite/Views/Movies/Partials/_AdvanceIndex.cshtml
@model IEnumerable<MovieWebsite.Models.Movies.MovieViewModel>
@{
    var roles = ViewBag.MovieRoles;
}
<p class="btn-group">
    <a asp-action="Create" role="button" class="btn btn-primary">Create New</a>
    <a asp-action="Index" role="button" class="btn btn-secondary">Reset list</a>
    <a asp-action="Index" asp-controller="People" class="btn btn-info">Manage people</a>
</p>
<div class="table-responsive-md">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Genres)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ReleaseYear)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nation)
                </th>
                <th>Manage</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        <img decoding="async" src="@("~/image/"+item.ImageName)" asp-append-version="true" class="movie-cover" />
                    </td>
                    <td>
                        <ul>
                            @foreach (var genre in item.Genres!)
                            {
                                <li>@genre</li>
                            }
                        </ul>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ReleaseYear)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nation)
                    </td>
                    <td>
                        <a asp-action="Index" asp-controller="Episodes" asp-route-id="@item.Id">Manage episodes</a>
                    </td>
                    <td>
                        <a class="btn btn-secondary" asp-action="Remove" asp-route-id="@item.Id" role="button">
                            @if (item.Deleted)
                            {
                                <p>Add</p>
                            }
                            else
                            {
                                <p>Remove</p>
                            }
                        </a>
                    </td>
                    <td>
                        <div class="btn-group" role="group">
                            <a class="btn btn-secondary" asp-action="Edit" asp-route-id="@item.Id" role="button">Edit</a>
                            <a class="btn btn-secondary" asp-action="Details" asp-route-id="@item.Id" role="button">Details</a>
                            <a class="btn btn-secondary" asp-action="Delete" asp-route-id="@item.Id" role="button">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

MovieWebsite/Views/Movies/Partials/_BasicIndex.cshtml
@model IEnumerable<MovieWebsite.Models.Movies.MovieViewModel>
@if (ViewBag.ResetList != null)
{
    <div class="btn-group">
        <a asp-action="Index" role="button" class="btn btn-secondary">Reset list</a>
    </div>
}
<div class="card-group" style="position:relative;">
    @foreach (var item in Model)
    {
        if(item.Deleted==false){
            <div class="">
                <a class="movie-item card nav-link text-dark" asp-action="Details" asp-route-id="@item.Id">
                    <img class="movie-cover card-img-top" decoding="async" src="@("~/image/"+item.ImageName)" asp-append-version="true" alt="Card cover image">
                    <div class="movie-overlay card-body">
                        <p class="card-title">@item.Title</p>
                    </div>
                </a>
            </div>
        }
    }
</div>

MovieWebsite/Views/Movies/Partials/_CommentCreate.cshtml
@model Comment
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@{
    var movieId = ViewBag.MovieId;
    var url = this.Context.Request.Path.Value;
}
@if(SignInManager.IsSignedIn(User)){
    <form asp-action="AddComment" asp-controller="Movies" >
        <span asp-validation-for="CommentDetail" class="text-warning"></span>
        <textarea placeholder="Nêu cảm nghĩ của bạn ở đây" asp-for="CommentDetail" cols="24" rows="5" class="form-control" style="resize:none"></textarea>
        <input name="movieId" type="hidden" value="@movieId" />
        <input name="currentUrl" type="hidden" value="@url" />
        <input class="btn btn-primary" type="submit" role="button" value="Add"/>
    </form>
}

MovieWebsite/Views/Movies/Partials/_CommentList.cshtml
@model IEnumerable<BusinessObject.Models.Comment>
@{
    
}
<div class="card-text" style="height:300px;overflow-y:scroll;">
    <div class="vstack gap-2 mx-auto">
        @if (Model.Any())
        {
            @foreach(var comment in Model){

                <div class="p-2 border-bottom rounded">
                    <div>
                        <strong>@comment.User.UserName</strong>
                    </div>
                    <div>
                        @comment.CommentDetail
                    </div>
                    <div>
                        <p> <small>@comment.CreatedDate</small></p>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="p-2 text-center">Không có bình luận nào</div>
        }
    </div>
</div>

MovieWebsite/Views/Movies/Partials/_EpisodeList.cshtml
@model IEnumerable<BusinessObject.Models.Episode>
<div class="card-body">
    @if(Model != null){
        <div class="btn-toolbar" role="toolbar">
            @foreach (var item in Model)
            {
                <div class="btn-group" role="group">
                    <a class="btn btn-secondary" asp-action="ViewMovie" asp-controller="Movies" asp-route-id="@item.Id" role="button">@item.Title</a>
                </div>
            }
        </div>
    }else{
        <div class="card-text">Chưa có tập nào</div>
    }
</div>

MovieWebsite/Views/Movies/Partials/_SelectGenre.cshtml
@model List<MovieWebsite.Models.Movies.ManageMovieGenreViewModel>
@{
    int i=0;
}

<div class="form-group">
    <label class="control-label">Genre</label>
    <div>
        @if(Model !=null){
            while (i < Model.Count)
            {
                <div class="btn-group-toggle" data-toggle="buttons">
                    <input type="hidden" asp-for="@Model[i].Name" />
                    <label class="btn btn-light" asp-for="@Model[i].Selected">
                        <input asp-for="@Model[i].Selected">@Model[i].Name
                    </label>
                </div>
                i++;
            }
        }
    </div>
</div>

MovieWebsite/Views/Movies/Partials/_SelectMoviePeople.cshtml
@model List<MovieWebsite.Models.Movies.ManageMoviePeopleModel>
@{
    int i = 0;
    IEnumerable<Role> roles = ViewBag.MovieRoles;
}

<div class="form-group">
    <label>People Invovle</label>
    <div class="card">
        @if (Model !=null)
        {
            if(roles.Any()){
                foreach (var role in roles)
                {
                    <label class="card-header">@role.Name</label>
                    <div class="card-body">
                        @if (Model.Any())
                        {
                            while (i < Model.Count)
                            {
                                if (Model[i].RoleId == role.Id)
                                {
                                    <div class="btn-group" data-toggle="button">
                                        <input type="hidden" asp-for="@Model[i].Name" />
                                        <input type="hidden" asp-for="@Model[i].RoleId" />
                                        <label class="btn btn-light" asp-for="@Model[i].Selected">
                                            <input asp-for="@Model[i].Selected"> @Model[i].Name
                                        </label>
                                    </div>
                                }
                                i++;
                            }
                            i = 0;
                        }
                        else
                        {
                            <a asp-action="Index" asp-controller="People">Manage people</a>
                        }
                    </div>
                    
                }
            }
        }
    </div>

</div>

MovieWebsite/Views/Movies/Partials/_SelectStatus.cshtml
@model List<MovieWebsite.Models.Movies.ManageMovieStatusModel>
@{
    int i=0;
}

<div class="form-group">
    <label class="control-label">Status</label>
    <div>
        @if(Model !=null){
            while (i < Model.Count)
            {
                <div class="btn-group-toggle" data-toggle="buttons">
                    <input type="hidden" asp-for="@Model[i].Name" />
                    <label class="btn btn-light" asp-for="@Model[i].Selected">
                        <input asp-for="@Model[i].Selected">@Model[i].Name
                    </label>
                </div>
                i++;
            }
        }
    </div>
</div>