MovieWebsite/Models/Movies/ManageMovieGenreViewModel.cs
namespace MovieWebsite.Models.Movies
{
    public class ManageMovieGenreViewModel
    {
        public string Name { get; set; } = null!;
        public bool Selected { get; set; } = false;
    }
}

MovieWebsite/Models/Movies/ManageMovieStatusModel.cs
namespace MovieWebsite.Models.Movies
{
    public class ManageMovieStatusModel
    {
        public string Name { get; set; } = null!;
        public bool Selected { get; set; } = false;
    }
}

MovieWebsite/Controllers/EpisodesController.cs
using BusinessObject.Models;
using DataAccess.Repository;
using DataAccess.Repository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MovieWebsite.Models.Episodes;

namespace MovieWebsite.Controllers
{
    public class EpisodesController : BaseController
    {
        private IEpisodeRepository episodeRepository;
        private IWebHostEnvironment _environment;
        public EpisodesController(IWebHostEnvironment environment)
        {
            episodeRepository = new EpisodeRepository();
            _environment = environment;
        }

        // GET: EpisodesController
        public ActionResult Index(string id,string? message)
        {
            var episodeList=episodeRepository.GetEpisodes().Where(e=>e.MovieId==id);
            ViewBag.MovieId = id;
            ViewBag.Message = message;
            return View(episodeList);
        }

        // GET: EpisodesController/Details/5
        public async Task<IActionResult> DetailsAsync(string id)
        {
            var episode=await episodeRepository.GetEpisodeByIdAsync(id);
            if (episode == null)
            {
                return NotFound();
            }
            return View(episode);
        }

        // GET: EpisodesController/Create
        public ActionResult Create(string id)
        {
            var episodeInput = new EpisodeInputModel {
                MovieId=id,
            };
            return View(episodeInput);
        }

        // POST: EpisodesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync(EpisodeInputModel episodeInput)
        {
            try
            {
                string epId=episodeInput.MovieId+"_"+episodeInput.Title;
                Episode ep = new()
                {
                    Id = epId,
                    MovieId=episodeInput.MovieId,
                    Title=episodeInput.Title,
                };
                if (episodeInput.VideoFile != null)
                {
                    ep.VideoName = await GetFileNameAsync(episodeInput.VideoFile, ep);
                }
                else
                {
                    ModelState.AddModelError("VideoFile", "This field must not be leave empty!");
                    throw new Exception();
                }
                await episodeRepository.AddEpisode(ep);
                return RedirectToAction(nameof(Index), new {id=ep.MovieId, message = "Create successfully" });
            }
            catch(FormatException fe)
            {
                ModelState.AddModelError("VideoFile", fe.Message);
                return View(episodeInput);
            }
            catch
            {
                return View(episodeInput);
            }
        }

        // GET: EpisodesController/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            var episode = await episodeRepository.GetEpisodeByIdAsync(id);
            if (episode == null)
            {
                return NotFound();
            }
            var episodeInput = new EpisodeInputModel
            {
                Id=episode.Id,
                MovieId=episode.MovieId,
                Title=episode.Title,
                VideoName=episode.VideoName!,
            };
            return View(episodeInput);
        }

        // POST: EpisodesController/Edit/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAsync(EpisodeInputModel episodeInput)
        {
            try
            {
                Episode ep =await episodeRepository.GetEpisodeByIdAsync(episodeInput.Id!);
                ep.Title = episodeInput.Title;
                if (episodeInput.VideoFile != null)
                {
                    RemoveVideoFile(episodeInput.VideoName, ep);
                    ep.VideoName = await GetFileNameAsync(episodeInput.VideoFile, ep);
                }
                else
                {
                    ep.VideoName = episodeInput.VideoName;
                }
                await episodeRepository.Update(ep);
                return RedirectToAction(nameof(Index), new { id = ep.MovieId, message = "Edit successfully" });
            }
            catch (FormatException fe)
            {
                ModelState.AddModelError("VideoFile", fe.Message);
                return View(episodeInput);
            }
            catch
            {
                return View(episodeInput);
            }
        }

        // GET: EpisodesController/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            var episode = await episodeRepository.GetEpisodeByIdAsync(id);
            if (episode == null)
            {
                return NotFound();
            }
            return View(episode);
        }

        // POST: EpisodesController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAsync(string id,string movieId)
        {
            try
            {
                var episode = await episodeRepository.GetEpisodeByIdAsync(id);
                if (episode == null)
                {
                    return NotFound();
                }
                RemoveVideoFile(episode.VideoName, episode);
                await episodeRepository.Delete(episode);
                return RedirectToAction(nameof(Index), new { id = movieId, message = "Delete successfully" });
            }
            catch
            {
                return RedirectToAction(nameof(Index), new { id = movieId, message = "Delete Fail" });
            }
        }
        
        //--------------------------------------------------------------------------------------
        private async Task<string> GetFileNameAsync(IFormFile file, Episode episode)
        {
            string wwwPath = _environment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(file.FileName);
            string path = wwwPath + "/video/";
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            path += $"/{episode.MovieId}/";
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            string extension = Path.GetExtension(file.FileName);
            if (!extension.Equals(".mp4"))
            {
                throw new FormatException("Can only accept .mp4 file at the momment");
            }
            fileName =episode.Id+ fileName + DateTime.Now.ToString("yymmssfff") + extension;
            path = Path.Combine(path, fileName);
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                await file.CopyToAsync(fileStream);
            }
            return fileName;
        }
        private void RemoveVideoFile(string? videoName, Episode episode)
        {
            if (!String.IsNullOrEmpty(videoName))
            {
                string path = Path.Combine(_environment.WebRootPath, "video",episode.MovieId, videoName);
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }
            }
        }
    }
}

MovieWebsite/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using DataAccess.Repository;
using MovieWebsite.Models.Movies;
using DataAccess.Repository.Interface;
using BusinessObject.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http.Extensions;
using MovieWebsite.Enums;

namespace MovieWebsite.Controllers
{
    public class MoviesController : BaseController
    {
        private readonly IMovieRepository movieRepository=null!;
        private readonly IGenreRepository genreRepository = null!;
        private readonly IMovieGenreRepository movieGenreRepository = null!;
        private readonly IApplicationUserRepository applicationUserRepository = null!;
        private readonly ICommentRepository commentRepository = null!;
        private readonly IEpisodeRepository episodeRepository;
        private readonly IWebHostEnvironment _environment;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IRoleRepository roleRepository;
        private readonly IPeopleRepository peopleRepository;
        private readonly IMoviePeopleRepository moviePeopleRepository;
        private readonly IMovieStatusRepository movieStatusRepository;
        private readonly IStatusRepository statusRepository;
        private readonly IRateRepository rateRepository;
        private readonly IFollowedMovieRepository followedMovieRepository;
        public MoviesController(IWebHostEnvironment environment, UserManager<ApplicationUser> userManager)
        {
            movieRepository = new MovieRepository();
            genreRepository = new GenreRepository();
            movieGenreRepository = new MovieGenreRepository();
            applicationUserRepository = new ApplicationUserRepository();
            commentRepository = new CommentRepository();
            episodeRepository = new EpisodeRepository();
            moviePeopleRepository= new MoviePeopleRepository();
            peopleRepository = new PeopleRepository();
            roleRepository = new RoleRepository();
            movieStatusRepository= new MovieStatusRepository();
            statusRepository= new StatusRepository();
            rateRepository= new RateRepository();
            followedMovieRepository= new FollowedMovieRepository();
            _environment = environment;
            _userManager = userManager;
        }
        [AllowAnonymous]
        // GET: MoviesController1
        public IActionResult Index(string? searchString, string? genreName, string? message, string? nation, IFormCollection collection)
        {
            List<MovieViewModel> model = new();
            try
            {
                IEnumerable<Movie> movies=movieRepository.GetMovies();
                var temp = movies.ToList();
                IEnumerable<Movie> searchResult;
                IEnumerable<Movie> filterResult;
                IEnumerable<Movie> nationResult;
                if (searchString != null)
                {
                    searchResult = movieRepository.GetMoviesByKeyWord(searchString).ToList();
                    movies=movies.IntersectBy(second:searchResult.Select(m=>m.Id), m => m.Id);
                    ViewBag.SearchString = searchString;
                }
                if (genreName != null)
                {
                    filterResult = movieRepository.GetMoviesByGenre(genreName).ToList();
                    movies = movies.IntersectBy(second: filterResult.Select(m => m.Id), m => m.Id);
                }
                if (nation != null)
                {
                    nationResult = movieRepository.GetMovies().Where(m => m.Nation == nation).ToList();
                    movies = movies.IntersectBy(second: nationResult.Select(m => m.Id), m => m.Id);
                }
                if(movies.Count() < temp.Count)
                {
                    ViewBag.ResetList = true;
                }
                if (movies.Any())
                {
                    foreach (var movie in movies)
                    {
                        var viewModel =GenerateMovieViewModel(movie);
                        model.Add(viewModel);
                    }
                }
                else
                {
                    throw new Exception("Sorry, we could not find your movie!");
                }
                ViewBag.Message = message;
            }
            catch (Exception ex)
            {
                ViewBag.Message=ex.Message;
            }
            return View(model);
        }
        [AllowAnonymous]
        // GET: MoviesController1/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (movieRepository.GetMovies() == null)
            {
                return View(null);
            }
            var movie = await movieRepository.GetMovieByIdAsync(id);
            var count = movie.Rates.Count;
            if (count > 0)
            {
                movie.Rating = (float)movie.Rates.Select(m => m.Rating).Sum()! /count;
                await movieRepository.Update(movie);
            }
            var movieView =GenerateMovieViewModel(movie);
            ViewBag.MovieRoles = roleRepository.GetRoles();
            return View(movieView);
        }

        // GET: MoviesController1/Create
        public IActionResult Create()
        {
            var movieInput = GenerateMovieInputModel();
            return View(movieInput);
        }

        // POST: MoviesController1/Create
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync(MovieInputModel movieInput)
        {
            try
            {
                movieInput.Id = movieInput.Title.Trim().ToLower();
                if (await ExistedTitleAsync(movieInput.Id))
                {
                    var movie = new Movie
                    {
                        Title = movieInput.Title,
                        Id = movieInput.Id,
                        Description = movieInput.Description,
                        ReleaseYear = movieInput.ReleaseYear,
                        Duration = movieInput.Duration,
                        Nation = movieInput.Nation,
                    };
                    if (movieInput.ImageFile != null)
                    {
                        movie.ImageName = await GetFileNameAsync(movieInput.ImageFile);
                        await AddSelectedAsync(movieInput);
                        await movieRepository.AddMovie(movie);
                    }
                    else
                    {
                        ModelState.AddModelError("ImageFile", "This field must not be leave empty!");
                        throw new Exception();
                    }
                }
                return RedirectToAction(nameof(Index), new { message = "Create successfully" });
            }
            catch
            {
                movieInput =GenerateMovieInputModel();
                return View(movieInput);
            }
        }

        // GET: MoviesController1/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            //find movie
            var movie = await movieRepository.GetMovieByIdAsync(id);
            MovieInputModel inputModel;
            if (movie == null)
            {
                return NotFound();
            }
            inputModel = GenerateMovieInputModel(movie);
            ViewBag.MovieRoles=roleRepository.GetRoles();
            //set datalist
            return View(inputModel);
        }

        // POST: MoviesController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MovieInputModel movieInput)
        {
            try
            {
                var movie = await movieRepository.GetMovieByIdAsync(movieInput.Id);
                if (movie == null)
                {
                    return NotFound();
                }
                //update movie----------------------------
                movie.Title = movieInput.Title;
                movie.Description = movieInput.Description;
                movie.ReleaseYear = movieInput.ReleaseYear;
                movie.Duration=movieInput.Duration;
                movie.Nation = movieInput.Nation;
                if (movieInput.ImageFile != null)
                {
                    RemoveImageFile(movie.ImageName);
                    movie.ImageName = await GetFileNameAsync(movieInput.ImageFile);
                }
                await movieRepository.Update(movie);
                //add selected genre-----------------------
                var movieGenres = movieGenreRepository.GetMovieGenresByMovieId(movieInput.Id);
                await movieGenreRepository.DeleteRange(movieGenres);
                var genres = movieInput.Genres.Where(m => m.Selected).Select(m => m.Name);
                foreach (var genreName in genres)
                {
                    var genre = await genreRepository.GetGenreByNameAsync(genreName);
                    var movieGenre = new MovieGenre
                    {
                        GenreId = genre.Id,
                        MovieId = movie.Id,
                        Id = movie.Id + genre.Id,
                    };
                    await movieGenreRepository.AddMovieGenre(movieGenre);
                }
                //add selected people----------------------
                var removedPeople= moviePeopleRepository.GetMoviePeople().Where(m=>m.MovieId==movieInput.Id).ToList();
                await moviePeopleRepository.DeleteRange(removedPeople);
                var peopleList = movieInput.MoviePeople.Where(m => m.Selected);
                foreach(var p in peopleList)
                {

MovieWebsite/Views/Movies/Create.cshtml
@model MovieWebsite.Models.Movies.MovieInputModel

@{
    ViewData["Title"] = "Create";
    var releaseYears = ViewBag.ReleaseYear;
    var nations = ViewBag.Nation;
}

<h1>Create</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <partial name="Partials/_SelectGenre" for="@Model.Genres" />
            <partial name="Partials/_SelectStatus" for="@Model.MovieStatuses" />
            <div class="form-group">
                <label asp-for="ReleaseYear" class="control-label"></label>
                <input asp-for="ReleaseYear" class="form-control" list="releaseYear" />
                <datalist id="releaseYear">
                    @if (releaseYears != null)
                    {
                        foreach (var year in releaseYears)
                        {
                            <option value="@year"></option>
                        }
                    }
                </datalist>
                <span asp-validation-for="ReleaseYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nation" class="control-label"></label>
                <input asp-for="Nation" class="form-control" list="nationList" />
                <datalist id="nationList">
                    @if (nations != null)
                    {
                        foreach (var nation in nations)
                        {
                            <option value="@nation"></option>
                        }
                    }
                </datalist>
                <span asp-validation-for="Nation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <partial name="Partials/_SelectMoviePeople" for="@Model.MoviePeople" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" cols="24" rows="5" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" accept="image/*"/>
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MovieWebsite/Views/Movies/Delete.cshtml
@model MovieWebsite.Models.Movies.MovieViewModel

@{
    ViewData["Title"] = "Delete";
    var roles = ViewBag.MovieRoles;
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row justify-content-between">
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>
        <dd class = "col-sm-8">
            <img decoding="async" src="@("~/image/"+Model.ImageName)" asp-append-version="true" class="movie-cover" />
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Rating) || @Model.Rates?.Count() lượt đánh giá
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Statuses)
        </dt>
        <dd class="col-sm-8 text-danger">
            @if (Model.Statuses is not null)
            {
                @string.Join(" ", Model.Statuses.ToList())
            }
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Genres)
        </dt>
        <dd class="col-sm-8">
            @if (Model.Genres is not null)
            {
                @string.Join(", ", Model.Genres.ToList())
            }
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.ReleaseYear)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Nation)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Nation)
        </dd>
        @foreach (Role role in roles)
        {
            <dt class="col-sm-4">@role.Name</dt>
            <dd class="col-sm-8">
                @{
                    var nameList = new List<string>();
                    foreach (var people in Model.MoviePeople!)
                    {
                        if (people.RoleId == role.Id)
                        {
                            nameList.Add(people.People.Name);
                        }
                    }
                }
                @string.Join(", ",nameList)
            </dd>
        }
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model=>model.Description)
        </dt>
        <dd class="col-sm-8">
            @if (Model?.Description is null)
            {
                <p class="card-text">N/A</p>
            }
            else
            {
                <p class="card-text">@Html.DisplayFor(model=>model.Description)</p>
            }
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MovieWebsite/Views/Movies/Details.cshtml
@using DataAccess.Repository
@using DataAccess.Repository.Interface
@model MovieWebsite.Models.Movies.MovieViewModel
@{
    ViewData["Title"] = Model.Title;
    ViewData["MovieId"] = Model.Id;
    var roles = ViewBag.MovieRoles;
    Layout = "_DetailsLayout";
}
<div>
    <div class="row justify-content-center">
        <h4 class="col-md-2">
            @Html.DisplayFor(model => model.Title)
        </h4>
    </div>
    <hr />
    <div class="row justify-content-between">
        <div class="col-md-3">
            <img decoding="async" src="@("~/image/"+Model.ImageName)" asp-append-version="true" class="movie-cover" />
        </div>
        <div class="col-md-7">
            <dl class="row">
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Rating)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Rating) || @Model.Rates?.Count() lượt đánh giá
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Statuses)
                </dt>
                <dd class="col-sm-8 text-danger">
                    @if (Model.Statuses is not null)
                    {
                        @string.Join(" ", Model.Statuses.ToList())
                    }
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Genres)
                </dt>
                <dd class="col-sm-8">
                    @if (Model.Genres is not null)
                    {
                        @string.Join(", ", Model.Genres.ToList())
                    }
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.ReleaseYear)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.ReleaseYear)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Duration)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Duration)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Nation)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Nation)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Views)
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Views)
                </dd>
                @foreach (Role role in roles)
                {
                    <dt class="col-sm-4">@role.Name</dt>
                    <dd class="col-sm-8">
                        @{
                            var nameList = new List<string>();
                            foreach (var people in Model.MoviePeople!)
                            {
                                if (people.RoleId == role.Id)
                                {
                                    nameList.Add(people.People.Name);
                                }
                            }
                        }
                        @string.Join(", ",nameList)
                    </dd>
                }
            </dl>
        </div>
    </div>
</div>
@if (User.IsInRole(Roles.SuperAdmin.ToString()))
{
    <div class="btn-group-sm">
        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id" role="button">Edit</a>
        <a class="btn btn-secondary" asp-action="Index" role="button">Back to List</a>
        <a class="btn btn-info" asp-action="Index" asp-controller="Episodes" asp-route-id="@Model!.Id" role="button">Manage episodes</a>
    </div>
}
<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                @Html.DisplayNameFor(model=>model.Episodes)
            </div>
            <partial name="Partials/_EpisodeList" model="Model?.Episodes" />
        </div>
    </div>
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                @Html.DisplayNameFor(model=>model.Description)
            </div>
            <div class="card-body">
                @if (Model?.Description is null)
                {
                    <p class="card-text">N/A</p>
                }
                else
                {
                    <p class="card-text">@Html.DisplayFor(model=>model.Description)</p>
                }
            </div>
        </div>
    </div>
</div>

MovieWebsite/Views/Movies/Index.cshtml
@model IEnumerable<MovieWebsite.Models.Movies.MovieViewModel>

@{
    ViewData["Title"] = "Index";
    var message = ViewBag.Message;
    var searchString = ViewBag.SearchString;
}

<h1>
    @if(searchString!=null){
        Output.WriteLine($"TỪ KHÓA:{searchString}");
    }
    else
    {
        Output.WriteLine($"DANH SÁCH PHIM");
    }
</h1>
<partial name="_Message" model="message" />
@if(User.IsInRole(role:Roles.SuperAdmin.ToString())){
    <partial name="Partials/_AdvanceIndex"/>
}else{
    <partial name="Partials/_BasicIndex" />
}